### ISSUE TITLE
Bump npm version of geneontology/wc-gocam-viz package to 1.0.0

### ISSUE THREAD

**Issue by dustine32** [alliance-genome/agr_ui#1272]
Please modify `package.json` to use the latest version `1.0.0` of `geneontology/wc-gocam-viz`:
https://github.com/alliance-genome/agr_ui/blob/d34bee4003c0fabe6d10d4e01b40d65b291f3434/package.json#L16
This change would fix https://github.com/geneontology/wc-gocam-viz/issues/34. Specifically, it would add some missing relation symbols to the legend:
![image](https://github.com/alliance-genome/agr_ui/assets/2678599/459e34df-0a55-4c22-9f0e-c3c23af2043d)

**Comment by oblodgett** [comment]
@dustine32 I believe you have access to create a PR and add this.

**Comment by dustine32** [comment]
Thanks @oblodgett! Just created the PR https://github.com/alliance-genome/agr_ui/pull/1274.

**Comment by dustine32** [comment]
Shows how much I know about updating the pathway widget! The simple version bump to `1.0.0` alone did not update the legend. Looking closer at the `agr_ui` implementation. The legend is sourced from a static image file:
https://github.com/alliance-genome/agr_ui/blob/55b116b8c1598449d7f87c39b785fcc3f658a29c/src/components/pathway/pathwayWidget.js#L17

The newer version of this web component changes how the legend should be implemented on the site so some more changes to `agr_ui` will be required.

**Comment by oblodgett** [comment]
@dustine32 I think this issue can be closed? We also use JIRA for all our issues. And the code can be tracked there.
