### ISSUE TITLE
Question: orthologs fetching limit of 10,000

### ISSUE THREAD

**Issue by dlrice** [alliance-genome/agr_ui#1365]
Hi, apologies for opening an issue for a question.

I am a developer for the uniprot website. We are investigating the incorporation of the data from the https://www.alliancegenome.org/api/gene/<id>/orthologs endpoint. Looking at your frontend codebase it looks like you add the limit of 10,000:

https://github.com/alliance-genome/agr_ui/blob/f1ab35ab8a869e2956e87c8c19e0fcce2f7988ed/src/hooks/useGeneOrthology.js#L6

because it looks to be a [paginated endpoint](https://github.com/alliance-genome/agr_java_software/blob/25a503bc35a82b7208d380a36c5abf1f39e06c6e/agr_api/src/main/java/org/alliancegenome/api/controller/OrthologyController.java#L39). I am guessing 10,000 is large enough that you wouldn't have to fetch more pages and the initial page is sufficient? Is that something that you guys just know from the data?

**Comment by cmpich** [comment]
Hi, you should be able to paginate through the set with the parameter
page
The full set of parameters you can find on our swagger page:
https://www.alliancegenome.org/swagger-ui/#/Genes/get_api_gene__id__orthologs

So, in your case you could retrieve the next set (of limit=10000) of ortholog records via
/api/gene/${geneId}/orthologs?filter.stringency=all&limit=10000&page=2

I hope that helps.

**Comment by dlrice** [comment]
Thanks for that 👍
